[package]
name = "aoc_2015_rust"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 0
panic = "abort"

[profile.release]
opt-level = 3
lto = "fat"
panic = "abort"
debug = false
strip = true

[dependencies]
md5 = "0.7"
